export class Constants{ 


    public static GetAbonnementsDetailsUrl="/api/abonnements/getAbonnementsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier AbonnementsController.cs*/
    public static GetAbonnementsEditUrl="/api/abonnements/getAbonnementsEditById";
    public static GetAllAbonnementsUrl="/api/abonnements/getAll";  /* même chaine que dans [Route("getall")] dans le fichier AbonnementsController.cs*/
    public static CreateAbonnementsUrl="/api/abonnements";  /* même chaine que dans [Route("create")] dans le fichier AbonnementsController.cs*/
    public static UpdateAbonnementsUrl="/api/abonnements";  /* même chaine que dans [Route("create")] dans le fichier AbonnementsController.cs*/
    public static GetAgendasDetailsUrl="/api/agendas/getAgendasDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier AgendasController.cs*/
    public static GetAgendasEditUrl="/api/agendas/getAgendasEditById";
    public static GetAllAgendasUrl="/api/agendas/getAll";  /* même chaine que dans [Route("getall")] dans le fichier AgendasController.cs*/
    public static CreateAgendasUrl="/api/agendas";  /* même chaine que dans [Route("create")] dans le fichier AgendasController.cs*/
    public static UpdateAgendasUrl="/api/agendas";  /* même chaine que dans [Route("create")] dans le fichier AgendasController.cs*/
    public static GetAgendas__TeleoperateursDetailsUrl="/api/agendas__teleoperateurs/getAgendas__TeleoperateursDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier Agendas__TeleoperateursController.cs*/
    public static GetAgendas__TeleoperateursEditUrl="/api/agendas__teleoperateurs/getAgendas__TeleoperateursEditById";
    public static GetAllAgendas__TeleoperateursUrl="/api/agendas__teleoperateurs/getAll";  /* même chaine que dans [Route("getall")] dans le fichier Agendas__TeleoperateursController.cs*/
    public static CreateAgendas__TeleoperateursUrl="/api/agendas__teleoperateurs";  /* même chaine que dans [Route("create")] dans le fichier Agendas__TeleoperateursController.cs*/
    public static UpdateAgendas__TeleoperateursUrl="/api/agendas__teleoperateurs";  /* même chaine que dans [Route("create")] dans le fichier Agendas__TeleoperateursController.cs*/
    public static GetAvisDetailsUrl="/api/avis/getAvisDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier AvisController.cs*/
    public static GetAvisEditUrl="/api/avis/getAvisEditById";
    public static GetAllAvisUrl="/api/avis/getAll";  /* même chaine que dans [Route("getall")] dans le fichier AvisController.cs*/
    public static CreateAvisUrl="/api/avis";  /* même chaine que dans [Route("create")] dans le fichier AvisController.cs*/
    public static UpdateAvisUrl="/api/avis";  /* même chaine que dans [Route("create")] dans le fichier AvisController.cs*/
    public static GetBanquesDetailsUrl="/api/banques/getBanquesDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier BanquesController.cs*/
    public static GetBanquesEditUrl="/api/banques/getBanquesEditById";
    public static GetAllBanquesUrl="/api/banques/getAll";  /* même chaine que dans [Route("getall")] dans le fichier BanquesController.cs*/
    public static CreateBanquesUrl="/api/banques";  /* même chaine que dans [Route("create")] dans le fichier BanquesController.cs*/
    public static UpdateBanquesUrl="/api/banques";  /* même chaine que dans [Route("create")] dans le fichier BanquesController.cs*/
    public static GetBoite__EnvoieDetailsUrl="/api/boite__envoie/getBoite__EnvoieDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier Boite__EnvoieController.cs*/
    public static GetBoite__EnvoieEditUrl="/api/boite__envoie/getBoite__EnvoieEditById";
    public static GetAllBoite__EnvoieUrl="/api/boite__envoie/getAll";  /* même chaine que dans [Route("getall")] dans le fichier Boite__EnvoieController.cs*/
    public static CreateBoite__EnvoieUrl="/api/boite__envoie";  /* même chaine que dans [Route("create")] dans le fichier Boite__EnvoieController.cs*/
    public static UpdateBoite__EnvoieUrl="/api/boite__envoie";  /* même chaine que dans [Route("create")] dans le fichier Boite__EnvoieController.cs*/
    public static GetContratsDetailsUrl="/api/contrats/getContratsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier ContratsController.cs*/
    public static GetContratsEditUrl="/api/contrats/getContratsEditById";
    public static GetAllContratsUrl="/api/contrats/getAll";  /* même chaine que dans [Route("getall")] dans le fichier ContratsController.cs*/
    public static CreateContratsUrl="/api/contrats";  /* même chaine que dans [Route("create")] dans le fichier ContratsController.cs*/
    public static UpdateContratsUrl="/api/contrats";  /* même chaine que dans [Route("create")] dans le fichier ContratsController.cs*/
    public static GetCriteresDetailsUrl="/api/criteres/getCriteresDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier CriteresController.cs*/
    public static GetCriteresEditUrl="/api/criteres/getCriteresEditById";
    public static GetAllCriteresUrl="/api/criteres/getAll";  /* même chaine que dans [Route("getall")] dans le fichier CriteresController.cs*/
    public static CreateCriteresUrl="/api/criteres";  /* même chaine que dans [Route("create")] dans le fichier CriteresController.cs*/
    public static UpdateCriteresUrl="/api/criteres";  /* même chaine que dans [Route("create")] dans le fichier CriteresController.cs*/
    public static GetEtats__AppelDetailsUrl="/api/etats__appel/getEtats__AppelDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier Etats__AppelController.cs*/
    public static GetEtats__AppelEditUrl="/api/etats__appel/getEtats__AppelEditById";
    public static GetAllEtats__AppelUrl="/api/etats__appel/getAll";  /* même chaine que dans [Route("getall")] dans le fichier Etats__AppelController.cs*/
    public static CreateEtats__AppelUrl="/api/etats__appel";  /* même chaine que dans [Route("create")] dans le fichier Etats__AppelController.cs*/
    public static UpdateEtats__AppelUrl="/api/etats__appel";  /* même chaine que dans [Route("create")] dans le fichier Etats__AppelController.cs*/
    public static GetEtats__ValidationDetailsUrl="/api/etats__validation/getEtats__ValidationDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier Etats__ValidationController.cs*/
    public static GetEtats__ValidationEditUrl="/api/etats__validation/getEtats__ValidationEditById";
    public static GetAllEtats__ValidationUrl="/api/etats__validation/getAll";  /* même chaine que dans [Route("getall")] dans le fichier Etats__ValidationController.cs*/
    public static CreateEtats__ValidationUrl="/api/etats__validation";  /* même chaine que dans [Route("create")] dans le fichier Etats__ValidationController.cs*/
    public static UpdateEtats__ValidationUrl="/api/etats__validation";  /* même chaine que dans [Route("create")] dans le fichier Etats__ValidationController.cs*/
    public static GetMissionsDetailsUrl="/api/missions/getMissionsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier MissionsController.cs*/
    public static GetMissionsEditUrl="/api/missions/getMissionsEditById";
    public static GetAllMissionsUrl="/api/missions/getAll";  /* même chaine que dans [Route("getall")] dans le fichier MissionsController.cs*/
    public static CreateMissionsUrl="/api/missions";  /* même chaine que dans [Route("create")] dans le fichier MissionsController.cs*/
    public static UpdateMissionsUrl="/api/missions";  /* même chaine que dans [Route("create")] dans le fichier MissionsController.cs*/
    public static GetModelesDetailsUrl="/api/modeles/getModelesDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier ModelesController.cs*/
    public static GetModelesEditUrl="/api/modeles/getModelesEditById";
    public static GetAllModelesUrl="/api/modeles/getAll";  /* même chaine que dans [Route("getall")] dans le fichier ModelesController.cs*/
    public static CreateModelesUrl="/api/modeles";  /* même chaine que dans [Route("create")] dans le fichier ModelesController.cs*/
    public static UpdateModelesUrl="/api/modeles";  /* même chaine que dans [Route("create")] dans le fichier ModelesController.cs*/
    public static GetMoyens__PaiementDetailsUrl="/api/moyens__paiement/getMoyens__PaiementDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier Moyens__PaiementController.cs*/
    public static GetMoyens__PaiementEditUrl="/api/moyens__paiement/getMoyens__PaiementEditById";
    public static GetAllMoyens__PaiementUrl="/api/moyens__paiement/getAll";  /* même chaine que dans [Route("getall")] dans le fichier Moyens__PaiementController.cs*/
    public static CreateMoyens__PaiementUrl="/api/moyens__paiement";  /* même chaine que dans [Route("create")] dans le fichier Moyens__PaiementController.cs*/
    public static UpdateMoyens__PaiementUrl="/api/moyens__paiement";  /* même chaine que dans [Route("create")] dans le fichier Moyens__PaiementController.cs*/
    public static GetOptionsDetailsUrl="/api/options/getOptionsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier OptionsController.cs*/
    public static GetOptionsEditUrl="/api/options/getOptionsEditById";
    public static GetAllOptionsUrl="/api/options/getAll";  /* même chaine que dans [Route("getall")] dans le fichier OptionsController.cs*/
    public static CreateOptionsUrl="/api/options";  /* même chaine que dans [Route("create")] dans le fichier OptionsController.cs*/
    public static UpdateOptionsUrl="/api/options";  /* même chaine que dans [Route("create")] dans le fichier OptionsController.cs*/
    public static GetQuestionnairesDetailsUrl="/api/questionnaires/getQuestionnairesDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier QuestionnairesController.cs*/
    public static GetQuestionnairesEditUrl="/api/questionnaires/getQuestionnairesEditById";
    public static GetAllQuestionnairesUrl="/api/questionnaires/getAll";  /* même chaine que dans [Route("getall")] dans le fichier QuestionnairesController.cs*/
    public static CreateQuestionnairesUrl="/api/questionnaires";  /* même chaine que dans [Route("create")] dans le fichier QuestionnairesController.cs*/
    public static UpdateQuestionnairesUrl="/api/questionnaires";  /* même chaine que dans [Route("create")] dans le fichier QuestionnairesController.cs*/
    public static GetQuestionsDetailsUrl="/api/questions/getQuestionsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier QuestionsController.cs*/
    public static GetQuestionsEditUrl="/api/questions/getQuestionsEditById";
    public static GetAllQuestionsUrl="/api/questions/getAll";  /* même chaine que dans [Route("getall")] dans le fichier QuestionsController.cs*/
    public static CreateQuestionsUrl="/api/questions";  /* même chaine que dans [Route("create")] dans le fichier QuestionsController.cs*/
    public static UpdateQuestionsUrl="/api/questions";  /* même chaine que dans [Route("create")] dans le fichier QuestionsController.cs*/
    public static GetReponsesDetailsUrl="/api/reponses/getReponsesDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier ReponsesController.cs*/
    public static GetReponsesEditUrl="/api/reponses/getReponsesEditById";
    public static GetAllReponsesUrl="/api/reponses/getAll";  /* même chaine que dans [Route("getall")] dans le fichier ReponsesController.cs*/
    public static CreateReponsesUrl="/api/reponses";  /* même chaine que dans [Route("create")] dans le fichier ReponsesController.cs*/
    public static UpdateReponsesUrl="/api/reponses";  /* même chaine que dans [Route("create")] dans le fichier ReponsesController.cs*/
    public static GetSecteurActivitesDetailsUrl="/api/secteuractivites/getSecteurActivitesDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier SecteurActivitesController.cs*/
    public static GetSecteurActivitesEditUrl="/api/secteuractivites/getSecteurActivitesEditById";
    public static GetAllSecteurActivitesUrl="/api/secteuractivites/getAll";  /* même chaine que dans [Route("getall")] dans le fichier SecteurActivitesController.cs*/
    public static CreateSecteurActivitesUrl="/api/secteuractivites";  /* même chaine que dans [Route("create")] dans le fichier SecteurActivitesController.cs*/
    public static UpdateSecteurActivitesUrl="/api/secteuractivites";  /* même chaine que dans [Route("create")] dans le fichier SecteurActivitesController.cs*/
    public static GetSocietesDetailsUrl="/api/societes/getSocietesDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier SocietesController.cs*/
    public static GetSocietesEditUrl="/api/societes/getSocietesEditById";
    public static GetAllSocietesUrl="/api/societes/getAll";  /* même chaine que dans [Route("getall")] dans le fichier SocietesController.cs*/
    public static CreateSocietesUrl="/api/societes";  /* même chaine que dans [Route("create")] dans le fichier SocietesController.cs*/
    public static UpdateSocietesUrl="/api/societes";  /* même chaine que dans [Route("create")] dans le fichier SocietesController.cs*/
    public static GetTeleoperateursDetailsUrl="/api/teleoperateurs/getTeleoperateursDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier TeleoperateursController.cs*/
    public static GetTeleoperateursEditUrl="/api/teleoperateurs/getTeleoperateursEditById";
    public static GetAllTeleoperateursUrl="/api/teleoperateurs/getAll";  /* même chaine que dans [Route("getall")] dans le fichier TeleoperateursController.cs*/
    public static CreateTeleoperateursUrl="/api/teleoperateurs";  /* même chaine que dans [Route("create")] dans le fichier TeleoperateursController.cs*/
    public static UpdateTeleoperateursUrl="/api/teleoperateurs";  /* même chaine que dans [Route("create")] dans le fichier TeleoperateursController.cs*/
    public static GetTeleoperateurs__MissionsDetailsUrl="/api/teleoperateurs__missions/getTeleoperateurs__MissionsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier Teleoperateurs__MissionsController.cs*/
    public static GetTeleoperateurs__MissionsEditUrl="/api/teleoperateurs__missions/getTeleoperateurs__MissionsEditById";
    public static GetAllTeleoperateurs__MissionsUrl="/api/teleoperateurs__missions/getAll";  /* même chaine que dans [Route("getall")] dans le fichier Teleoperateurs__MissionsController.cs*/
    public static CreateTeleoperateurs__MissionsUrl="/api/teleoperateurs__missions";  /* même chaine que dans [Route("create")] dans le fichier Teleoperateurs__MissionsController.cs*/
    public static UpdateTeleoperateurs__MissionsUrl="/api/teleoperateurs__missions";  /* même chaine que dans [Route("create")] dans le fichier Teleoperateurs__MissionsController.cs*/
    public static GetTicketsDetailsUrl="/api/tickets/getTicketsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier TicketsController.cs*/
    public static GetTicketsEditUrl="/api/tickets/getTicketsEditById";
    public static GetAllTicketsUrl="/api/tickets/getAll";  /* même chaine que dans [Route("getall")] dans le fichier TicketsController.cs*/
    public static CreateTicketsUrl="/api/tickets";  /* même chaine que dans [Route("create")] dans le fichier TicketsController.cs*/
    public static UpdateTicketsUrl="/api/tickets";  /* même chaine que dans [Route("create")] dans le fichier TicketsController.cs*/
    public static GetTrunkSIPDetailsUrl="/api/trunksip/getTrunkSIPDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier TrunkSIPController.cs*/
    public static GetTrunkSIPEditUrl="/api/trunksip/getTrunkSIPEditById";
    public static GetAllTrunkSIPUrl="/api/trunksip/getAll";  /* même chaine que dans [Route("getall")] dans le fichier TrunkSIPController.cs*/
    public static CreateTrunkSIPUrl="/api/trunksip";  /* même chaine que dans [Route("create")] dans le fichier TrunkSIPController.cs*/
    public static UpdateTrunkSIPUrl="/api/trunksip";  /* même chaine que dans [Route("create")] dans le fichier TrunkSIPController.cs*/
    public static GetTypeAppelsDetailsUrl="/api/typeappels/getTypeAppelsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier TypeAppelsController.cs*/
    public static GetTypeAppelsEditUrl="/api/typeappels/getTypeAppelsEditById";
    public static GetAllTypeAppelsUrl="/api/typeappels/getAll";  /* même chaine que dans [Route("getall")] dans le fichier TypeAppelsController.cs*/
    public static CreateTypeAppelsUrl="/api/typeappels";  /* même chaine que dans [Route("create")] dans le fichier TypeAppelsController.cs*/
    public static UpdateTypeAppelsUrl="/api/typeappels";  /* même chaine que dans [Route("create")] dans le fichier TypeAppelsController.cs*/
    public static GetTypeMissionsDetailsUrl="/api/typemissions/getTypeMissionsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier TypeMissionsController.cs*/
    public static GetTypeMissionsEditUrl="/api/typemissions/getTypeMissionsEditById";
    public static GetAllTypeMissionsUrl="/api/typemissions/getAll";  /* même chaine que dans [Route("getall")] dans le fichier TypeMissionsController.cs*/
    public static CreateTypeMissionsUrl="/api/typemissions";  /* même chaine que dans [Route("create")] dans le fichier TypeMissionsController.cs*/
    public static UpdateTypeMissionsUrl="/api/typemissions";  /* même chaine que dans [Route("create")] dans le fichier TypeMissionsController.cs*/
    public static GetTypeProspectsDetailsUrl="/api/typeprospects/getTypeProspectsDetailsById";  /* même chaine que dans [Route("getbyId")] dans le fichier TypeProspectsController.cs*/
    public static GetTypeProspectsEditUrl="/api/typeprospects/getTypeProspectsEditById";
    public static GetAllTypeProspectsUrl="/api/typeprospects/getAll";  /* même chaine que dans [Route("getall")] dans le fichier TypeProspectsController.cs*/
    public static CreateTypeProspectsUrl="/api/typeprospects";  /* même chaine que dans [Route("create")] dans le fichier TypeProspectsController.cs*/
    public static UpdateTypeProspectsUrl="/api/typeprospects";  /* même chaine que dans [Route("create")] dans le fichier TypeProspectsController.cs*/

}

