export namespace  Enums{
  
    export enum StatutTeleoperateursTeleoperateurs  {
        " Auto-entrepreneur"="1 ",
        " Société (EURL, SARL, SA, SAS)"="2 ",
        " Entreprise Individuelle"="3 ",
        " Portage salarial"="4 ",
        " Agent commercial"="5 ",

    }
    export enum Envoie_MailEtats__ValidationEtats__Validation  {
        "Envoyer les mails / SMS de confirmation au prospect "=" false",
        "Ne pas envoyer les mails / SMS de confirmation au prospect "=" true",

    }
    export enum email_Confirmation_rdvMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum smS_Confirmation_rdvMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum email_Rappel_rdvMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum smS_Rappel_rdvMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum email_TeleoperateurMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum visialisation_ItineraireMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum reception_Fiche_rdvMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum reception_Fiche_rdV_CommercialMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum reception_Mail_RecapitulatifMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum visialisation_DetailsMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum placement_RDVMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum affichage_tempsMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum autoriser_SuperpositionMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum geolocalisationMissionsMissions  {
        "Oui"=" true",
        "Non"=" false",

    }
    export enum realisation_MissionMissionsMissions  {
        "Système d'appel de la plateforme"="1",
        "Logiciel d'appel ou softphone (protocole 'tel:')"="2",
        "Autre solution de téléphonie (appels désactivés sur JobPhoning)" ="3",
        "Téléphone portable"="4",
        "Système d'appel de secours"="5",
        "Système d'appel de secours bis"="6",

    }
    export enum Libelle_Type_ProspectTypeProspectsTypeProspects  {
        " Vente aux particuliers (BtoC)"="1 ",
        " Ventre aux professionnels (BtoB)"="2 ",

    }
    export enum Type_ProspectsMissionsMissions  {
        " Professionnels (BtoB)"="1 ",
        " Particuliers (BtoC)"="2 ",

    }
    export enum BesoinMissionsMissions  {
        " Régulier"="1 ",
        " Ponctuel"="2 ",

    }
    export enum TypeBanquesBanques  {
        " Compte bancaire"="1 ",
        " PayPal"="2 ",

    }
    export enum EtatBoite__EnvoieBoite__Envoie  {
        "Validation en attente"="1",
        "Validé"="2",

    }
    export enum SecuriteBoite__EnvoieBoite__Envoie  {
        " Aucune"="1 ",
        " TLS"="2 ",
        " SSL"="3 ",

    }
    export enum Unite_Duree_RDVMissionsMissions  {
        " Heures"="1 ",
        " Minutes"="2 ",

    }
    export enum Libelle_Type_ProspectTypeMissionsTypeMissions  {
        " Vente aux particuliers (BtoC)"="1 ",
        " Ventre aux professionnels (BtoB)"="2 ",

    }
    export enum Type_ConnexionTeleoperateursTeleoperateurs  {
        " WiFi (sans-fil)"="1 ",
        " Câble ethernet (filaire)"="2 ",

    }
    export enum Libelle_Type_MissionTypeMissionsTypeMissions  {
        " Prise de RDV."="1 ",
        " Qualifications de fichiers."="2 ",
        " Création de trafic."="3 ",
        " Enquêtes et sondages téléphonique."="4 ",
        " Détection de projet."="5 ",

    }
    export enum Comment_connuSocietesSocietes  {
        " Google"="1 ",
        " Indeed"="10 ",
        " Seniors à votre service"="11 ",
        " 1001 Auto-Entrepreneurs"="12 ",
        " Autre:"="13 ",
        " Youtube"="2 ",
        " Forum"="3 ",
        " Bouche à oreille"="4 ",
        " J'ai reçu un email"="5 ",
        " Facebook"="6 ",
        " LinkedIn"="7 ",
        " Jooble"="8 ",
        " Pole Emploi"="9 ",

    }
    export enum ActionEtats__ValidationEtats__Validation  {
        " Supprimer le RDV de l’agenda"="1 ",
        " Empécher la remontée de la fiche"="2 ",
        " Annuler les mails / SMS de rappel du RDV au prospect"="3 ",

    }
    export enum ExistanceSocietesSocietes  {
        "En cours de création "=" false",
        "Existante "=" true",

    }
    export enum PaysTeleoperateursTeleoperateurs  {
        "Afghanistan"="1",
        "Antigua-et-Barbuda"="10",
        "Îles Marshall"="100",
        "Îles Mineures Éloignées des États-Unis"="101",
        "Îles Salomon"="102",
        "Îles Turks et Caïques"="103",
        "Îles Vierges Britanniques"="104",
        "Îles Vierges des États-Unis"="105",
        "Inde"="106",
        "Indonésie"="107",
        "Iraq"="108",
        "Irlande"="109",
        "Antilles Néerlandaises"="11",
        "Islande"="110",
        "Italie"="111",
        "Jamahiriya Arabe Libyenne"="112",
        "Jamaïque"="113",
        "Japon"="114",
        "Jordanie"="115",
        "Kazakhstan"="116",
        "Kenya"="117",
        "Kirghizistan"="118",
        "Kiribati"="119",
        "Arabie Saoudite"="12",
        "Koweït"="120",
        "L’ex-République Yougoslave de Macédoine"="121",
        "Lesotho"="122",
        "Lettonie"="123",
        "Liban"="124",
        "Libéria"="125",
        "Liechtenstein"="126",
        "Lituanie"="127",
        "Luxembourg"="128",
        "Macao"="129",
        "Argentine"="13",
        "Madagascar"="130",
        "Malaisie"="131",
        "Malawi"="132",
        "Maldives"="133",
        "Mali"="134",
        "Malte"="135",
        "Maroc"="136",
        "Martinique"="137",
        "Maurice"="138",
        "Mauritanie"="139",
        "Arménie"="14",
        "Mayotte"="140",
        "Mexique"="141",
        "Monaco"="142",
        "Mongolie"="143",
        "Montserrat"="144",
        "Mozambique"="145",
        "Myanmar"="146",
        "Namibie"="147",
        "Nauru"="148",
        "Népal"="149",
        "Aruba"="15",
        "Nicaragua"="150",
        "Niger"="151",
        "Nigéria"="152",
        "Niué"="153",
        "Non défini"="154",
        "Norvège"="155",
        "Nouvelle-Calédonie"="156",
        "Nouvelle-Zélande"="157",
        "Oman"="158",
        "Ouganda"="159",
        "Australie"="16",
        "Ouzbékistan"="160",
        "Pakistan"="161",
        "Palaos"="162",
        "Panama"="163",
        "Papouasie-Nouvelle-Guinée"="164",
        "Paraguay"="165",
        "Pays-Bas"="166",
        "Pérou"="167",
        "Philippines"="168",
        "Pitcairn"="169",
        "Autriche"="17",
        "Pologne"="170",
        "Polynésie Française"="171",
        "Porto Rico"="172",
        "Portugal"="173",
        "Qatar"="174",
        "République Arabe Syrienne"="175",
        "République Centrafricaine"="176",
        "République de Corée"="177",
        "République de Moldova"="178",
        "République Démocratique du Congo"="179",
        "Azerbaïdjan"="18",
        "République Démocratique Populaire Lao"="180",
        "République Dominicaine"="181",
        "République du Congo"="182",
        "République Islamique d’Iran"="183",
        "République Populaire Démocratique de Corée"="184",
        "République Tchèque"="185",
        "République-Unie de Tanzanie"="186",
        "Réunion"="187",
        "Roumanie"="188",
        "Royaume-Uni"="189",
        "Bahamas"="19",
        "Rwanda"="190",
        "Sahara Occidental"="191",
        "Saint-Kitts-et-Nevis"="192",
        "Saint-Marin"="193",
        "Saint-Pierre-et-Miquelon"="194",
        "Saint-Siège (état de la Cité du Vatican)"="195",
        "Saint-Vincent-et-les Grenadines"="196",
        "Sainte-Hélène"="197",
        "Sainte-Lucie"="198",
        "Samoa"="199",
        "Afrique du Sud"="2",
        "Bahreïn"="20",
        "Samoa Américaines"="200",
        "Sao Tomé-et-Principe"="201",
        "Sénégal"="202",
        "Serbie-et-Monténégro"="203",
        "Seychelles"="204",
        "Sierra Leone"="205",
        "Singapour"="206",
        "Slovaquie"="207",
        "Slovénie"="208",
        "Somalie"="209",
        "Bangladesh"="21",
        "Soudan"="210",
        "Sri Lanka"="211",
        "Suède"="212",
        "Suisse"="213",
        "Suriname"="214",
        "Svalbard etÎle Jan Mayen"="215",
        "Swaziland"="216",
        "Tadjikistan"="217",
        "Taïwan"="218",
        "Tchad"="219",
        "Barbade"="22",
        "Terres Australes Françaises"="220",
        "Territoire Britannique de l’Océan Indien"="221",
        "Bélarus"="23",
        "Belgique"="24",
        "Belize"="25",
        "Bénin"="26",
        "Bermudes"="27",
        "Bhoutan"="28",
        "Bolivie"="29",
        "Albanie"="3",
        "Bosnie-Herzégovine"="30",
        "Botswana"="31",
        "Brésil"="32",
        "Brunéi Darussalam"="33",
        "Bulgarie"="34",
        "Burkina Faso"="35",
        "Burundi"="36",
        "Cambodge"="37",
        "Cameroun"="38",
        "Canada"="39",
        "Algérie"="4",
        "Cap-vert"="40",
        "Chili"="41",
        "Chine"="42",
        "Chypre"="43",
        "Colombie"="44",
        "Comores"="45",
        "Costa Rica"="46",
        "Côte d’Ivoire"="47",
        "Croatie"="48",
        "Cuba"="49",
        "Allemagne"="5",
        "Danemark"="50",
        "Djibouti"="51",
        "Dominique"="52",
        "Égypte"="53",
        "El Salvador"="54",
        "Émirats Arabes Unis"="55",
        "Équateur"="56",
        "Érythrée"="57",
        "Espagne"="58",
        "Estonie"="59",
        "Andorre"="6",
        "États Fédérés de Micronésie"="60",
        "États-Unis"="61",
        "Éthiopie"="62",
        "Fédération de Russie"="63",
        "Fidji"="64",
        "Finlande"="65",
        "France"="66",
        "Gabon"="67",
        "Gambie"="68",
        "Géorgie"="69",
        "Angola"="7",
        "Géorgie du Sud et les Îles Sandwich du Sud"="70",
        "Ghana"="71",
        "Gibraltar"="72",
        "Grèce"="73",
        "Grenade"="74",
        "Groenland"="75",
        "Guadeloupe"="76",
        "Guam"="77",
        "Guatemala"="78",
        "Guinée"="79",
        "Anguilla"="8",
        "Guinée Équatoriale"="80",
        "Guinée-Bissau"="81",
        "Guyana"="82",
        "Guyane Française"="83",
        "Haïti"="84",
        "Honduras"="85",
        "Hong-Kong"="86",
        "Hongrie"="87",
        "Île Bouvet"="88",
        "Île Christmas"="89",
        "Antarctique"="9",
        "Île de Man"="90",
        "Île Norfolk"="91",
        "Îles (malvinas) Falkland"="92",
        "Îles Åland"="93",
        "Îles Caïmanes"="94",
        "Îles Cocos (Keeling)"="95",
        "Îles Cook"="96",
        "Îles Féroé"="97",
        "Îles Heard et Mcdonald"="98",
        "Îles Mariannes du Nord"="99",

    }
    export enum PaysSocietesSocietes  {
        "Afghanistan"="1",
        "Antigua-et-Barbuda"="10",
        "Îles Marshall"="100",
        "Îles Mineures Éloignées des États-Unis"="101",
        "Îles Salomon"="102",
        "Îles Turks et Caïques"="103",
        "Îles Vierges Britanniques"="104",
        "Îles Vierges des États-Unis"="105",
        "Inde"="106",
        "Indonésie"="107",
        "Iraq"="108",
        "Irlande"="109",
        "Antilles Néerlandaises"="11",
        "Islande"="110",
        "Italie"="111",
        "Jamahiriya Arabe Libyenne"="112",
        "Jamaïque"="113",
        "Japon"="114",
        "Jordanie"="115",
        "Kazakhstan"="116",
        "Kenya"="117",
        "Kirghizistan"="118",
        "Kiribati"="119",
        "Arabie Saoudite"="12",
        "Koweït"="120",
        "L’ex-République Yougoslave de Macédoine"="121",
        "Lesotho"="122",
        "Lettonie"="123",
        "Liban"="124",
        "Libéria"="125",
        "Liechtenstein"="126",
        "Lituanie"="127",
        "Luxembourg"="128",
        "Macao"="129",
        "Argentine"="13",
        "Madagascar"="130",
        "Malaisie"="131",
        "Malawi"="132",
        "Maldives"="133",
        "Mali"="134",
        "Malte"="135",
        "Maroc"="136",
        "Martinique"="137",
        "Maurice"="138",
        "Mauritanie"="139",
        "Arménie"="14",
        "Mayotte"="140",
        "Mexique"="141",
        "Monaco"="142",
        "Mongolie"="143",
        "Montserrat"="144",
        "Mozambique"="145",
        "Myanmar"="146",
        "Namibie"="147",
        "Nauru"="148",
        "Népal"="149",
        "Aruba"="15",
        "Nicaragua"="150",
        "Niger"="151",
        "Nigéria"="152",
        "Niué"="153",
        "Non défini"="154",
        "Norvège"="155",
        "Nouvelle-Calédonie"="156",
        "Nouvelle-Zélande"="157",
        "Oman"="158",
        "Ouganda"="159",
        "Australie"="16",
        "Ouzbékistan"="160",
        "Pakistan"="161",
        "Palaos"="162",
        "Panama"="163",
        "Papouasie-Nouvelle-Guinée"="164",
        "Paraguay"="165",
        "Pays-Bas"="166",
        "Pérou"="167",
        "Philippines"="168",
        "Pitcairn"="169",
        "Autriche"="17",
        "Pologne"="170",
        "Polynésie Française"="171",
        "Porto Rico"="172",
        "Portugal"="173",
        "Qatar"="174",
        "République Arabe Syrienne"="175",
        "République Centrafricaine"="176",
        "République de Corée"="177",
        "République de Moldova"="178",
        "République Démocratique du Congo"="179",
        "Azerbaïdjan"="18",
        "République Démocratique Populaire Lao"="180",
        "République Dominicaine"="181",
        "République du Congo"="182",
        "République Islamique d’Iran"="183",
        "République Populaire Démocratique de Corée"="184",
        "République Tchèque"="185",
        "République-Unie de Tanzanie"="186",
        "Réunion"="187",
        "Roumanie"="188",
        "Royaume-Uni"="189",
        "Bahamas"="19",
        "Rwanda"="190",
        "Sahara Occidental"="191",
        "Saint-Kitts-et-Nevis"="192",
        "Saint-Marin"="193",
        "Saint-Pierre-et-Miquelon"="194",
        "Saint-Siège (état de la Cité du Vatican)"="195",
        "Saint-Vincent-et-les Grenadines"="196",
        "Sainte-Hélène"="197",
        "Sainte-Lucie"="198",
        "Samoa"="199",
        "Afrique du Sud"="2",
        "Bahreïn"="20",
        "Samoa Américaines"="200",
        "Sao Tomé-et-Principe"="201",
        "Sénégal"="202",
        "Serbie-et-Monténégro"="203",
        "Seychelles"="204",
        "Sierra Leone"="205",
        "Singapour"="206",
        "Slovaquie"="207",
        "Slovénie"="208",
        "Somalie"="209",
        "Bangladesh"="21",
        "Soudan"="210",
        "Sri Lanka"="211",
        "Suède"="212",
        "Suisse"="213",
        "Suriname"="214",
        "Svalbard etÎle Jan Mayen"="215",
        "Swaziland"="216",
        "Tadjikistan"="217",
        "Taïwan"="218",
        "Tchad"="219",
        "Barbade"="22",
        "Terres Australes Françaises"="220",
        "Territoire Britannique de l’Océan Indien"="221",
        "Bélarus"="23",
        "Belgique"="24",
        "Belize"="25",
        "Bénin"="26",
        "Bermudes"="27",
        "Bhoutan"="28",
        "Bolivie"="29",
        "Albanie"="3",
        "Bosnie-Herzégovine"="30",
        "Botswana"="31",
        "Brésil"="32",
        "Brunéi Darussalam"="33",
        "Bulgarie"="34",
        "Burkina Faso"="35",
        "Burundi"="36",
        "Cambodge"="37",
        "Cameroun"="38",
        "Canada"="39",
        "Algérie"="4",
        "Cap-vert"="40",
        "Chili"="41",
        "Chine"="42",
        "Chypre"="43",
        "Colombie"="44",
        "Comores"="45",
        "Costa Rica"="46",
        "Côte d’Ivoire"="47",
        "Croatie"="48",
        "Cuba"="49",
        "Allemagne"="5",
        "Danemark"="50",
        "Djibouti"="51",
        "Dominique"="52",
        "Égypte"="53",
        "El Salvador"="54",
        "Émirats Arabes Unis"="55",
        "Équateur"="56",
        "Érythrée"="57",
        "Espagne"="58",
        "Estonie"="59",
        "Andorre"="6",
        "États Fédérés de Micronésie"="60",
        "États-Unis"="61",
        "Éthiopie"="62",
        "Fédération de Russie"="63",
        "Fidji"="64",
        "Finlande"="65",
        "France"="66",
        "Gabon"="67",
        "Gambie"="68",
        "Géorgie"="69",
        "Angola"="7",
        "Géorgie du Sud et les Îles Sandwich du Sud"="70",
        "Ghana"="71",
        "Gibraltar"="72",
        "Grèce"="73",
        "Grenade"="74",
        "Groenland"="75",
        "Guadeloupe"="76",
        "Guam"="77",
        "Guatemala"="78",
        "Guinée"="79",
        "Anguilla"="8",
        "Guinée Équatoriale"="80",
        "Guinée-Bissau"="81",
        "Guyana"="82",
        "Guyane Française"="83",
        "Haïti"="84",
        "Honduras"="85",
        "Hong-Kong"="86",
        "Hongrie"="87",
        "Île Bouvet"="88",
        "Île Christmas"="89",
        "Antarctique"="9",
        "Île de Man"="90",
        "Île Norfolk"="91",
        "Îles (malvinas) Falkland"="92",
        "Îles Åland"="93",
        "Îles Caïmanes"="94",
        "Îles Cocos (Keeling)"="95",
        "Îles Cook"="96",
        "Îles Féroé"="97",
        "Îles Heard et Mcdonald"="98",
        "Îles Mariannes du Nord"="99",

    }
    export enum HeureAgendasAgendas  {
        " 0h - 1h"="1 ",
        " 10h - 11h"="10 ",
        " 11h - 12h"="11 ",
        " 12h - 13h"="12 ",
        " 13h - 14h"="13 ",
        " 14h - 15h"="14 ",
        " 15h - 16h"="15 ",
        " 16h - 17h"="16 ",
        " 17h - 18h"="17 ",
        " 18h - 19h"="18 ",
        " 19h - 20h"="19 ",
        " 2h - 3h"="2 ",
        " 1h - 2h"="2 ",
        " 20h - 21h"="20 ",
        " 21h - 22h"="21 ",
        " 22h - 23h"="22 ",
        " 23h - 0h"="23 ",
        " 3h - 4h"="3 ",
        " 4h - 5h"="4 ",
        " 5h - 6h"="5 ",
        " 6h - 7h"="6 ",
        " 7h - 8h"="7 ",
        " 8h - 9h"="8 ",
        " 9h - 10h"="9 ",

    }
    export enum StatutSocietesSocietes  {
        " Auto-entrepreneur"="1 ",
        " Société (EURL, SARL, SA, SAS)"="2 ",
        " Entreprise Individuelle"="3 ",
        " Portage salarial"="4 ",
        " Agent commercial"="5 ",

    }
    export enum Periode_EngagementAbonnementsAbonnements  {
        " 12 mois"="1 ",
        " 6 mois"="2 ",
        " 3 mois"="3 ",

    }
    export enum JourAgendasAgendas  {
        " Lundi"="1 ",
        " Mardi"="2 ",
        " Mercredi"="3 ",
        " Jeudi"="4 ",
        " Vendredi"="5 ",
        " Samedi"="6 ",
        " Dimanche"="7 ",

    }
    export enum Domaine_ActiviteSocietesSocietes  {
        " Vente de produits"="1 ",
        " Industrie"="10 ",
        " Amélioration de l'habitat (fenêtres, isolation, toiture...)"="11 ",
        " Chauffage, climatisation, énergies renouvelables"="12 ",
        " Sécurité (alarme, controle d'accès, gardiennage, télésurveillance...)"="13 ",
        " Conseil (accompagnement, management, gestion...)"="14 ",
        " Autre...."="15 ",
        " Communication (site internet, publicité...)"="16 ",
        " Conseil (management, gestion...)"="17 ",
        " Formation professionnelle (opco, cpf...)"="18 ",
        " Communication digitale (site internet, application..."="19 ",
        " Informatique (infogérance, sécurité, support/maintenance)"="2 ",
        " Publicité (encarts journaux/magazines, TV, véhicules, bornes, digital...)"="20 ",
        " Evènementiel (salons, séminaires, foires, portes ouvertes, street marketing)"="21 ",
        " Énergie (fournisseurs, courtiers...)"="22 ",
        " Formation médicale (dpc)"="23 ",
        " Logiciels, CRM, plateformes"="24 ",
        " Télécommunications (courtage, opérateurs / fournisseurs d'accès)"="25 ",
        " Formation"="26 ",
        " Télécommunications (matériel, logiciel)"="3 ",
        " Assurance, mutuelle, prévoyance, crédits, retraite"="4 ",
        " Gestion de patrimoine, défiscalisation"="5 ",
        " Immobilier"="6 ",
        " Bien-être (beauté, nutrition...)"="7 ",
        " Service à la personne"="8 ",
        " Prestation de service (RH, externalisation diverses...)"="9 ",

    }
    export enum Libelle_Type_AppelTypeAppelsTypeAppels  {
        " Appels sortants"="1 ",
        " Appels entrants"="2 ",
        " Aucun des deux"="3 ",

    }
    export enum Assujetti_TVASocietesSocietes  {
        "Société non assujettie à la TVA "=" false",
        "Société assujettie à la TVA "=" true",

    }
    export enum EtatTicketsTickets  {
        " Ouvert"="1 ",
        " Répondu"="2 ",
        " fermé"="3 ",

    }
    export enum Mission_ConcerneTicketsTickets  {
        " Aucune"="1 ",
        " Toutes les mission"="2 ",

    }
    export enum Nbre_AnneeTypeAppelsTypeAppels  {
        " De 1 à 3 ans"=" 2 ",
        " Plus de 5 ans"=" 4 ",
        " Moins de 1 an"="1 ",
        " De 3 à 5 ans"="3 ",

    }
    export enum Assujetti_TVATeleoperateursTeleoperateurs  {
        "Société non assujettie à la TVA "=" false",
        "Société assujettie à la TVA "=" true",

    }
    export enum Secteur_Activite_SouhaiteeSecteurActivitesSecteurActivites  {
        " Quel(s) secteur(s) d'activité vous intéressent"="1 ",
        " Dans quels secteurs d'activité avez-vous travaillé avec succès"="2 ",
        " Dans quels secteurs d'activité ne souhaitez-vous pas travailler"="3 ",

    }
    export enum Type_EtatEtats__AppelEtats__Appel  {
        " Etat validant"="1 ",
        " Etat non validant"="2 ",
        " Rappel"="3 ",
        " Rappel validant"="4 ",

    }
    export enum Libelle_Type_Secteur_ActiviteSecteurActivitesSecteurActivites  {
        " Vente de produits"="1 ",
        " Industrie"="10 ",
        " Amélioration de l'habitat (fenêtres, isolation, toiture...)"="11 ",
        " Chauffage, climatisation, énergies renouvelables"="12 ",
        " Sécurité (alarme, controle d'accès, gardiennage, télésurveillance...)"="13 ",
        " Conseil (accompagnement, management, gestion...)"="14 ",
        " Autre...."="15 ",
        " Communication (site internet, publicité...)"="16 ",
        " Conseil (management, gestion...)"="17 ",
        " Formation professionnelle (opco, cpf...)"="18 ",
        " Communication digitale (site internet, application..."="19 ",
        " Informatique (infogérance, sécurité, support/maintenance)"="2 ",
        " Publicité (encarts journaux/magazines, TV, véhicules, bornes, digital...)"="20 ",
        " Evènementiel (salons, séminaires, foires, portes ouvertes, street marketing)"="21 ",
        " Énergie (fournisseurs, courtiers...)"="22 ",
        " Formation médicale (dpc)"="23 ",
        " Logiciels, CRM, plateformes"="24 ",
        " Télécommunications (courtage, opérateurs / fournisseurs d'accès)"="25 ",
        " Formation"="26 ",
        " Télécommunications (matériel, logiciel)"="3 ",
        " Assurance, mutuelle, prévoyance, crédits, retraite"="4 ",
        " Gestion de patrimoine, défiscalisation"="5 ",
        " Immobilier"="6 ",
        " Bien-être (beauté, nutrition...)"="7 ",
        " Service à la personne"="8 ",
        " Prestation de service (RH, externalisation diverses...)"="9 ",

    }
    export enum CiviliteTeleoperateursTeleoperateurs  {
        " Mr"="1 ",
        " Mme"="2 ",
        " Mlle"="3 ",

    }
    export enum Type_Mission_SouhaiteeTypeMissionsTypeMissions  {
        " Quel(s) type(s) de mission vous intéressent"="1 ",
        " Sur quels types de missions avez-vous déjà travaillé"="2 ",
        " Sur quels types de missions ne souhaitez-vous pas travailler"="3 ",

    }
    export enum Type_FichierMissionsMissions  {
        " Fichier non qualifié"="1 ",
        " Fichier ciblé"="2 ",
        " Fichier qualifié"="3 ",
        " Fichier de leads"="4 ",

    }
    export enum Type_MissionEtats__AppelEtats__Appel  {
        " Prise de RDV."="1 ",
        " Qualifications de fichiers."="2 ",
        " Création de trafic."="3 ",
        " Enquêtes et sondages téléphonique."="4 ",
        " Détection de projet."="5 ",

    }
    export enum BoiteGmailBoite__EnvoieBoite__Envoie  {
        "Non "=" false",
        "Oui "=" true",

    }
    export enum Rendez_VousMissionsMissions  {
        "  jour"="1 ",
        " semaine"="2 ",
        " mois"="3 ",

    }
    export enum CiviliteSocietesSocietes  {
        " Mr"="1 ",
        " Mme"="2 ",
        " Mlle"="3 ",

    }
    export enum PaysAgendas__TeleoperateursAgendas__Teleoperateurs  {
        "Afghanistan"="1",
        "Antigua-et-Barbuda"="10",
        "Îles Marshall"="100",
        "Îles Mineures Éloignées des États-Unis"="101",
        "Îles Salomon"="102",
        "Îles Turks et Caïques"="103",
        "Îles Vierges Britanniques"="104",
        "Îles Vierges des États-Unis"="105",
        "Inde"="106",
        "Indonésie"="107",
        "Iraq"="108",
        "Irlande"="109",
        "Antilles Néerlandaises"="11",
        "Islande"="110",
        "Italie"="111",
        "Jamahiriya Arabe Libyenne"="112",
        "Jamaïque"="113",
        "Japon"="114",
        "Jordanie"="115",
        "Kazakhstan"="116",
        "Kenya"="117",
        "Kirghizistan"="118",
        "Kiribati"="119",
        "Arabie Saoudite"="12",
        "Koweït"="120",
        "L’ex-République Yougoslave de Macédoine"="121",
        "Lesotho"="122",
        "Lettonie"="123",
        "Liban"="124",
        "Libéria"="125",
        "Liechtenstein"="126",
        "Lituanie"="127",
        "Luxembourg"="128",
        "Macao"="129",
        "Argentine"="13",
        "Madagascar"="130",
        "Malaisie"="131",
        "Malawi"="132",
        "Maldives"="133",
        "Mali"="134",
        "Malte"="135",
        "Maroc"="136",
        "Martinique"="137",
        "Maurice"="138",
        "Mauritanie"="139",
        "Arménie"="14",
        "Mayotte"="140",
        "Mexique"="141",
        "Monaco"="142",
        "Mongolie"="143",
        "Montserrat"="144",
        "Mozambique"="145",
        "Myanmar"="146",
        "Namibie"="147",
        "Nauru"="148",
        "Népal"="149",
        "Aruba"="15",
        "Nicaragua"="150",
        "Niger"="151",
        "Nigéria"="152",
        "Niué"="153",
        "Non défini"="154",
        "Norvège"="155",
        "Nouvelle-Calédonie"="156",
        "Nouvelle-Zélande"="157",
        "Oman"="158",
        "Ouganda"="159",
        "Australie"="16",
        "Ouzbékistan"="160",
        "Pakistan"="161",
        "Palaos"="162",
        "Panama"="163",
        "Papouasie-Nouvelle-Guinée"="164",
        "Paraguay"="165",
        "Pays-Bas"="166",
        "Pérou"="167",
        "Philippines"="168",
        "Pitcairn"="169",
        "Autriche"="17",
        "Pologne"="170",
        "Polynésie Française"="171",
        "Porto Rico"="172",
        "Portugal"="173",
        "Qatar"="174",
        "République Arabe Syrienne"="175",
        "République Centrafricaine"="176",
        "République de Corée"="177",
        "République de Moldova"="178",
        "République Démocratique du Congo"="179",
        "Azerbaïdjan"="18",
        "République Démocratique Populaire Lao"="180",
        "République Dominicaine"="181",
        "République du Congo"="182",
        "République Islamique d’Iran"="183",
        "République Populaire Démocratique de Corée"="184",
        "République Tchèque"="185",
        "République-Unie de Tanzanie"="186",
        "Réunion"="187",
        "Roumanie"="188",
        "Royaume-Uni"="189",
        "Bahamas"="19",
        "Rwanda"="190",
        "Sahara Occidental"="191",
        "Saint-Kitts-et-Nevis"="192",
        "Saint-Marin"="193",
        "Saint-Pierre-et-Miquelon"="194",
        "Saint-Siège (état de la Cité du Vatican)"="195",
        "Saint-Vincent-et-les Grenadines"="196",
        "Sainte-Hélène"="197",
        "Sainte-Lucie"="198",
        "Samoa"="199",
        "Afrique du Sud"="2",
        "Bahreïn"="20",
        "Samoa Américaines"="200",
        "Sao Tomé-et-Principe"="201",
        "Sénégal"="202",
        "Serbie-et-Monténégro"="203",
        "Seychelles"="204",
        "Sierra Leone"="205",
        "Singapour"="206",
        "Slovaquie"="207",
        "Slovénie"="208",
        "Somalie"="209",
        "Bangladesh"="21",
        "Soudan"="210",
        "Sri Lanka"="211",
        "Suède"="212",
        "Suisse"="213",
        "Suriname"="214",
        "Svalbard etÎle Jan Mayen"="215",
        "Swaziland"="216",
        "Tadjikistan"="217",
        "Taïwan"="218",
        "Tchad"="219",
        "Barbade"="22",
        "Terres Australes Françaises"="220",
        "Territoire Britannique de l’Océan Indien"="221",
        "Bélarus"="23",
        "Belgique"="24",
        "Belize"="25",
        "Bénin"="26",
        "Bermudes"="27",
        "Bhoutan"="28",
        "Bolivie"="29",
        "Albanie"="3",
        "Bosnie-Herzégovine"="30",
        "Botswana"="31",
        "Brésil"="32",
        "Brunéi Darussalam"="33",
        "Bulgarie"="34",
        "Burkina Faso"="35",
        "Burundi"="36",
        "Cambodge"="37",
        "Cameroun"="38",
        "Canada"="39",
        "Algérie"="4",
        "Cap-vert"="40",
        "Chili"="41",
        "Chine"="42",
        "Chypre"="43",
        "Colombie"="44",
        "Comores"="45",
        "Costa Rica"="46",
        "Côte d’Ivoire"="47",
        "Croatie"="48",
        "Cuba"="49",
        "Allemagne"="5",
        "Danemark"="50",
        "Djibouti"="51",
        "Dominique"="52",
        "Égypte"="53",
        "El Salvador"="54",
        "Émirats Arabes Unis"="55",
        "Équateur"="56",
        "Érythrée"="57",
        "Espagne"="58",
        "Estonie"="59",
        "Andorre"="6",
        "États Fédérés de Micronésie"="60",
        "États-Unis"="61",
        "Éthiopie"="62",
        "Fédération de Russie"="63",
        "Fidji"="64",
        "Finlande"="65",
        "France"="66",
        "Gabon"="67",
        "Gambie"="68",
        "Géorgie"="69",
        "Angola"="7",
        "Géorgie du Sud et les Îles Sandwich du Sud"="70",
        "Ghana"="71",
        "Gibraltar"="72",
        "Grèce"="73",
        "Grenade"="74",
        "Groenland"="75",
        "Guadeloupe"="76",
        "Guam"="77",
        "Guatemala"="78",
        "Guinée"="79",
        "Anguilla"="8",
        "Guinée Équatoriale"="80",
        "Guinée-Bissau"="81",
        "Guyana"="82",
        "Guyane Française"="83",
        "Haïti"="84",
        "Honduras"="85",
        "Hong-Kong"="86",
        "Hongrie"="87",
        "Île Bouvet"="88",
        "Île Christmas"="89",
        "Antarctique"="9",
        "Île de Man"="90",
        "Île Norfolk"="91",
        "Îles (malvinas) Falkland"="92",
        "Îles Åland"="93",
        "Îles Caïmanes"="94",
        "Îles Cocos (Keeling)"="95",
        "Îles Cook"="96",
        "Îles Féroé"="97",
        "Îles Heard et Mcdonald"="98",
        "Îles Mariannes du Nord"="99",

    }
    export enum Visibilite_MissionMissionsMissions  {
        " Appel d'offres"="1 ",
        " Mission privée"="2 ",
        " Mission publique"="3 ",
        " Mission internel"="4 ",

    }
    export enum ExistanceTeleoperateursTeleoperateurs  {
        "En cours de création "=" false",
        "Existante "=" true",

    }
    export enum Comment_connuTeleoperateursTeleoperateurs  {
        " Pole Emploi"="10 ",
        " Indeed"="11 ",
        " Seniors à votre service"="12 ",
        " 1001 Auto-Entrepreneurs"="13 ",
        " Autre:"="14 ",
        " Google"="2 ",
        " Youtube"="3 ",
        " Forum"="4 ",
        " Bouche à oreille"="5 ",
        " J'ai reçu un email"="6 ",
        " Facebook"="7 ",
        " LinkedIn"="8 ",
        " Jooble"="9 ",

    }
    export enum Fichier_CibleEtats__AppelEtats__Appel  {
        " BtoB"="1 ",
        " BtoC"="2 ",

    }
    export enum Categorie_TicketTicketsTickets  {
        " Service commercial"="1 ",
        " Service technique"="2 ",

    }
    export enum EtatTrunkSIPTrunkSIP  {
        " En attente de validation"="1 ",
        " Validé"="2 ",

    }


}

